users = {
    "admin": "password"
}

YOUR_NAME = ''

SONOS_IP = ''
HUE_IP = ''
HUE_USERNAME = ''

SEXY_TIME_PLAYLIST_NAME = "Sexy Time"
SEXY_TIME_FIRST_TRACK = "01 - Lets Get It On.mp3"
SEXY_TIME_DIMMER_SECONDS = 10
SEXY_TIME_DIMMER_BRIGHTNESS = 125

PARTY_TIME_PLAYLIST_NAME = "Party Time"

ARRIVING_HOME_PLAYLIST_NAME = "Arriving Home"
ARRIVING_HOME_DIMMER_SECONDS = 3
ARRIVING_HOME_DIMMER_BRIGHTNESS = 170
ARRIVING_HOME_VOLUME = 20
